### ISSUE TITLE
No syncs for a week from Runkeeper

### ISSUE THREAD

**Issue by groegl** [cpfair/tapiriik#365]
Have been using Tapiriik for more than a year to sync btw Strava, Runkeeper, Dropbox and Endomondo. My Runkeeper runs have not been syncing since July 24th when the last successful sync took place. Since then I have 3 runs on Runkeeper but they don't sync anymore - I have tried disconnecting Runkeeper and adding it again to Tapiriik but that doesn't fix the issue. Have also checked that runs are definitely not marked private - so seems to be a problem with the service.

**Comment by theinmostdens** [comment]
Same here.

**Comment by 2600box** [comment]
yup. this sucks. it was working perfectly for years.

**Comment by elskewe** [comment]
I think this is related to #362.

**Comment by erlendl** [comment]
I have the same problem. No activities synched from Runkeeper to Strava, Endomondo and DropBox after 23th of July. My next activity that was up for synch is from 27th of July, so the synch stopped working between 23th and 27th of July.
I have disconnected all services and re-connected and also paid for automatic synch. I have no trouble with connecting services like the issue #362 describes.
None of the activities are private - identical to what @groegl har reported.
I have only tested synching from Runkeeper to other services. I will try tracking with eg Strava to check if the problem is related to Runkeeper beeing the synching source.
I hope @cpfair is able to look into the issue since I much enjoy this service - and pay for it :-)

**Comment by DustinNorman** [comment]
I'm seeing this too. I was also seeing #362 but that seems to be resolved now.

**Comment by jminke** [comment]
also here: Strava to Runkeeper does no longer sync.
"Some activities could not be synchronized." as status. Under "Your activities" there are no activities listed

**Comment by creubank** [comment]
Same issue; the activities page shows runkeeper activities as being synced, but they do not show up in my runkeeper feed.  (citystrides has a similar issue related to a drastic reduction in the number of runkeeper API calls allowed).

**Comment by erlendl** [comment]
In my recent test it seems like the problem is syncing into Strava. When I removed Strava, activities were successfully synced from Runkeeper to DropBox and Endomondo. Adding back Strava made all syncing stop again.

**Comment by elskewe** [comment]
Seems to be partially fixed for me. While syncing to Runkeeper is still unreliable (many activities with "There was a problem uploading this activity to Runkeeper."), at least it works for some activities.

**Comment by np1** [comment]
I am still not anything synced from Strava to Runkeeper since end of July.

**Comment by jminke** [comment]
seems to be working for me now, all activities are synched (runkeeper to strava and vice versa)

**Comment by groegl** [comment]
still not working for me - last successful sync on July 24th

**Comment by groegl** [comment]
Suddenly all working for me - all activities since July 24th were successfully synced a few hours ago. Last night I disconnected and reconnected all services (Strava, Runkeeper, Endomondo) which might have something to do with it.. or it was just fixed.

**Comment by felixwillmann** [comment]
still not working for me - Strava to Runkeeper works, but Runkeeper runs don't even get synced to Dropbox after years of working flawlessly

**Comment by mbmb65** [comment]
not working for me!! only "queuing" for hours (!!) with no progress :-(
I use endomodo and dropbox

**Comment by 2600box** [comment]
i hope it gets fixed eventually...

**Comment by Raphioud** [comment]
Doesn't work yet. I hope it will be soon repaired :(

**Comment by Raphioud** [comment]
It works again ! Tks !

**Comment by 2600box** [comment]
i had to unlink all my accounts and relink, but it seems to be working. yay

**Comment by e85134** [comment]
Don't use Runkeeper much (like just one active friend), but just noticed no syncs since June 30th.  I relinked tapiriik, but no luck.  I'm going to further troubleshoot.

**Comment by Raphioud** [comment]
Damned... 'doesn't work anymore. Same for you e85134 & 2600box ?

**Comment by e85134** [comment]
My last run synced fine.  It took a day to show up on Runkeeper, and I can't confirm exactly which source it synced from but it seems to work now.  I'll sync again after the weekend when I have another run.

**Comment by 2600box** [comment]
synced my run and cycle last night. one was rk -> strava and the other was strava -> rk

**Comment by groegl** [comment]
Fixed
