### ISSUE TITLE
There was a problem accessing your Strava account. 

### ISSUE THREAD

**Issue by yogurd** [cpfair/tapiriik#456]
There was a problem accessing your Strava account. Use the button below to reauthorize tapiriik to access your account. Garmin Connect User? You may need to sign in directly on Garmin Connect and reset your password to meet new security requirements - then come back here and try again.

1. I did that - it didnt work
2. I removed tapiriik from strava and added again - it didnt work

I dont use Garmin Connect

**Comment by LiveB0mb** [comment]
Same issue here for two days. 
I tried remove and add strava again and nothing happen

**Comment by Tazzie79** [comment]
Same issue since yesterday. Also disconnecting or reauthorizing does not work.

**Comment by bodily11** [comment]
Maybe related to this issue, but I did a workout 14 hours ago that hasn't synced yet. It usually syncs every hour or so. Maybe something is down on Tapiiriik...?

**Comment by Tazzie79** [comment]
Seems fixed now. Already 2 runs synced.

**Comment by RobDickson** [comment]
I noticed that today (I hadn't noticed it before because I normally do multi-sport activities, which Tapiriik ignores). When I clicked on the link to reauthorise with Strava, I logged into Strava, but wasn't asked anything about authorisation. Tapiriik no longer gives an error, so let's see if yesterday's run appears in Strava.....

I also looked at my settings and the synchronise from date has been changed to 31/05/18. This might have been me, but I don't think so. Looks like there's been some corruption on Tapiriik.

**Comment by RobDickson** [comment]
All seems OK now - I have my Strava trophy.

**Comment by pblvsk** [comment]
Issue still present for me, missing 2 rides from 23.08 (Strava > Endomondo)
